---
title: "Visualización DataViz"
output: pdf_document
params:
  n: NA
  a: NA
  b: NA
  c: NA
  d: NA
  show_text: NA
  choices: NA
---




```{r conditional_block, echo=FALSE, results='asis', eval=params$show_text}

library(ggplot2)
if(params$choices[1] == "1. Market Share"){
cat("## Visualización de Market Share")
cat("\n")
params$a
} else if(params$choices[1] == "2. Evolucion"){
cat("## Visualización de Evolución")
cat("\n")
params$b  
} else if(params$choices[1] == "3. Contexto"){ 
cat("## Visualización de Contexto")
cat("\n")
params$c
} else if(params$choices[1] == "4. Variacion"){
cat("## Visualización de Variación")
cat("\n")
params$d 
}


```

```{r conditional_block1, echo=FALSE, results='asis', eval=params$show_text}
cat("\n")
```


```{r conditional_block2, echo=FALSE, results='asis', eval=params$show_text}

library(ggplot2)
if(params$choices[2] == "1. Market Share"){
cat("## Visualización de Market Share")
cat("\n")
params$a
} else if(params$choices[2] == "2. Evolucion"){
cat("## Visualización de Evolución")
cat("\n")
params$b  
} else if(params$choices[2] == "3. Contexto"){ 
cat("## Visualización de Contexto")
cat("\n")
params$c
} else if(params$choices[2] == "4. Variacion"){
cat("## Visualización de Variación")
cat("\n")
params$d 
}


```

```{r conditional_block3, echo=FALSE, results='asis', eval=params$show_text}
cat("\n")
```


```{r conditional_block4, echo=FALSE, results='asis', eval=params$show_text}

library(ggplot2)
if(params$choices[3] == "1. Market Share"){
cat("## Visualización de Market Share")
cat("\n")
params$a
} else if(params$choices[3] == "2. Evolucion"){
cat("## Visualización de Evolución")
cat("\n")
params$b  
} else if(params$choices[3] == "3. Contexto"){ 
cat("## Visualización de Contexto")
cat("\n")
params$c
} else if(params$choices[3] == "4. Variacion"){
cat("## Visualización de Variación")
cat("\n")
params$d 
}


```

```{r conditional_block5, echo=FALSE, results='asis', eval=params$show_text}
cat("\n")
```


```{r conditional_block6, echo=FALSE, results='asis', eval=params$show_text}

library(ggplot2)
if(params$choices[4] == "1. Market Share"){
cat("## Visualización de Market Share")
cat("\n")
params$a
} else if(params$choices[4] == "2. Evolucion"){
cat("## Visualización de Evolución")
cat("\n")
params$b  
} else if(params$choices[4] == "3. Contexto"){ 
cat("## Visualización de Contexto")
cat("\n")
params$c
} else if(params$choices[4] == "4. Variacion"){
cat("## Visualización de Variación")
cat("\n")
params$d 
}


```

```{r conditional_block7, echo=FALSE, results='asis', eval=params$show_text}
cat("\n")
```